version: "3.9"

services:
  vault:
    image: vault:1.13.3
    container_name: "vault"
    ports:
      - "8200:8200"
    command: vault server --config=/vault/vault.json
    volumes:
      - "./vault_config/vault.json:/vault/vault.json:ro"
      - "./vault_config/file:/vault/file:rw"
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
      VAULT_ADDRESS: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - vault

networks:
  vault:
    external: true